[package]
name = "Arin"
version = "3.0.0"
edition = "2024"

[dependencies]
may_minihttp = { path = "may_http" }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
# env_logger = "0.11"
crossbeam-channel = "0.5"
simd-json = { version = "0.17.0", features = ["serde_impl"] }

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
debug = false
panic = "abort"
overflow-checks = false

[build]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+avx2,+bmi2,+fma",
    "-C", "opt-level=3",
    "-C", "lto=fat",
    "-C", "codegen-units=1",
    "-C", "inline-threshold=500",
    "-C", "prefer-dynamic=no"
]
