[package]
name = "Arin"
version = "2.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "net", "time", "sync", "macros", "signal"] }
hyper = { version = "1", default-features = false, features = ["server", "http1"] }
hyper-util = { version = "0.1", default-features = false, features = ["tokio", "client-legacy", "http1"] }
http-body-util = "0.1"
bytes = "1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
socket2 = { version = "0.6", default-features = false, features = ["all"] }
blake3 = { version = "1", default-features = false, features = ["std"] }
crossbeam-channel = "0.5"
num_cpus = "1.16"
rsa = { version = "0.9", default-features = false, features = ["std"] }
rand = "0.8"
chacha20poly1305 = "0.10"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
debug = false
panic = "abort"
overflow-checks = false
strip = true

[profile.release.package.blake3]
opt-level = 3
